/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthVehiclesImport } from './routes/_auth/vehicles'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthAddVehicleImport } from './routes/_auth/add-vehicle'
import { Route as AuthVehiclesVehicleIdImport } from './routes/_auth/vehicles_/$vehicleId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVehiclesRoute = AuthVehiclesImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAddVehicleRoute = AuthAddVehicleImport.update({
  id: '/add-vehicle',
  path: '/add-vehicle',
  getParentRoute: () => AuthRoute,
} as any)

const AuthVehiclesVehicleIdRoute = AuthVehiclesVehicleIdImport.update({
  id: '/vehicles_/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/add-vehicle': {
      id: '/_auth/add-vehicle'
      path: '/add-vehicle'
      fullPath: '/add-vehicle'
      preLoaderRoute: typeof AuthAddVehicleImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/vehicles': {
      id: '/_auth/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthVehiclesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/vehicles_/$vehicleId': {
      id: '/_auth/vehicles_/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthVehiclesVehicleIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAddVehicleRoute: typeof AuthAddVehicleRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthVehiclesRoute: typeof AuthVehiclesRoute
  AuthVehiclesVehicleIdRoute: typeof AuthVehiclesVehicleIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAddVehicleRoute: AuthAddVehicleRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthVehiclesRoute: AuthVehiclesRoute,
  AuthVehiclesVehicleIdRoute: AuthVehiclesVehicleIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/add-vehicle': typeof AuthAddVehicleRoute
  '/dashboard': typeof AuthDashboardRoute
  '/vehicles': typeof AuthVehiclesRoute
  '/vehicles/$vehicleId': typeof AuthVehiclesVehicleIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/add-vehicle': typeof AuthAddVehicleRoute
  '/dashboard': typeof AuthDashboardRoute
  '/vehicles': typeof AuthVehiclesRoute
  '/vehicles/$vehicleId': typeof AuthVehiclesVehicleIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/add-vehicle': typeof AuthAddVehicleRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/vehicles': typeof AuthVehiclesRoute
  '/_auth/vehicles_/$vehicleId': typeof AuthVehiclesVehicleIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/add-vehicle'
    | '/dashboard'
    | '/vehicles'
    | '/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/add-vehicle'
    | '/dashboard'
    | '/vehicles'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/add-vehicle'
    | '/_auth/dashboard'
    | '/_auth/vehicles'
    | '/_auth/vehicles_/$vehicleId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/add-vehicle",
        "/_auth/dashboard",
        "/_auth/vehicles",
        "/_auth/vehicles_/$vehicleId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/add-vehicle": {
      "filePath": "_auth/add-vehicle.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/vehicles": {
      "filePath": "_auth/vehicles.tsx",
      "parent": "/_auth"
    },
    "/_auth/vehicles_/$vehicleId": {
      "filePath": "_auth/vehicles_/$vehicleId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
